development:
  adapter: mysql2
  database: joke
  host: localhost
  port: 3306
  username: 'root'
  password: '123456'
  charset: utf8mb4
  encoding: utf8mb4
  collation: utf8mb4_unicode_ci

test:
  adapter: mysql2
  database: juche
  host: localhost
  port: 3306
  username: 'root'
  password: '123'

production:
  adapter: mysql2
  database: joke
  host: infhaps.com
  port: 3306
  username: 'root'
  password: '1234'
  charset: utf8mb4
  encoding: utf8mb4
  collation: utf8mb4_unicode_ci
